# Generated by Django 4.2.4 on 2023-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdescription', models.CharField(max_length=40)),
                ('creator', models.CharField(max_length=40)),
                ('clang', models.CharField(choices=[('Eng', 'English'), ('Hin', 'Hindi')], max_length=40)),
                ('cprice', models.IntegerField()),
                ('cimage', models.ImageField(default='images/noimage.png', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
