# Generated by Django 4.2.4 on 2023-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_course_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cdescription',
            field=models.CharField(max_length=250),
        ),
    ]
