# Generated by Django 4.2.4 on 2023-08-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_orders_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
    ]
