# Generated by Django 4.2.4 on 2023-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_myorders_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='orderdate',
            field=models.DateField(null=True),
        ),
    ]
